### ISSUE TITLE
/usr/include/features.h:367:12: fatal error: 'sys/cdefs.h' file not found

### ISSUE THREAD

**Issue by OuterSpaceTears** [EveripediaNetwork/Everipedia#1]
I want to generate article. ABI file，
@FortisFortuna 

`feng@feng-B250-HD3P:~/workSpace/eos/build/tools/myC/article$ ../../eoscpp -g article.abi article.hpp
In file included from /home/feng/workSpace/eos/build/tools/myC/article/article.hpp:30:
In file included from /usr/local/include/eosiolib/eosio.hpp:6:
In file included from /usr/local/include/eosiolib/types.hpp:6:
In file included from /usr/local/include/eosiolib/types.h:7:
In file included from /usr/include/stdint.h:25:
/usr/include/features.h:367:12: fatal error: 'sys/cdefs.h' file not found
#  include <sys/cdefs.h>
           ^~~~~~~~~~~~~
1 error generated.
Error while processing /home/feng/workSpace/eos/build/tools/myC/article/article.hpp`

**Comment by k26dr** [comment]
This is a local build error, not related to the overall software. Closing.
