### ISSUE TITLE
Ties are not rejected

### ISSUE THREAD

**Issue by contractormario** [EveripediaNetwork/Everipedia#13]
https://github.com/EveripediaNetwork/Everipedia/blob/ffb719ff59f863e32759fdecbeef6feffd73913b/eparticlectr/eparticlectr.cpp#L268

**Comment by FortisFortuna** [comment]
Thanks. Will fix in the next version

**Comment by k26dr** [comment]
Fixed in [2eacc34](https://github.com/EveripediaNetwork/Everipedia/commit/2eacc34042d026dbb3c372bb75d0ce7f54d2aa55) and deployed to mainnet
