### ISSUE TITLE
Investigate if voting system is vulnerable to sniping

### ISSUE THREAD

**Issue by contractormario** [EveripediaNetwork/Everipedia#14]
https://en.wikipedia.org/wiki/Auction_sniping

**Comment by FortisFortuna** [comment]
We are well aware of this. Right now, it is simple majority because it is an MVP. Later versions will have different algorithms for votes.

**Comment by peterjmarko** [comment]
@k26dr, this system is the opposite of what is needed. Suppose that there are 11 votes with 6 for and 5 against. As per the above, the editor making the change would get the highest reward possible in this situation. Now suppose that the voting is 5 for and 6 against: the editor would lose his/her stake. Take the other two extremes: 11 for and 0 against - smallest possible reward; and 0 for and 11 against - the same loss of stake as before. So now you have a reward system that motivates editors to make controversial changes and removes the incentive for making obvious corrections. It also wouldn't penalize editors for making obviously bad edits. The result will be an encyclopedia full of mistakes and controversial content.

What is needed is a system where the reward/penalty increases with consensus agreement/disagreement. For example:

`For_Against_Reward_Penalty`
`11_____0______1.0_________`
`_8_____3______0.3_________`
`_6_____5______0.1_________`
`_5_____6_____________0.1__`
`_3_____8_____________0.3__`
`_0____11_____________1.0__`

**Comment by k26dr** [comment]
you're misunderstanding the system. everybody doesn't get rewarded based on the final tally. you get rewarded based on how close the vote is at the time of **your** vote

**Comment by k26dr** [comment]
The code for this is now on the master branch if you want to check it out.

**Comment by contractormario** [comment]
What do you think about having votes weighted to counter possible abuse near the end of the voting period (sniping)? I think strength of your votes being proportional to time left (in %) would combat this. For example:
vote strength = 100% at the beginning of the voting period
vote strength = 5% when only 5% of voting period remaining
and so on down to zero (limit approaching zero)
technically you'd still be able to change the outcome if you had A LOT of tokens but at the same time if someone happened to outvote you in time you'd lose significantly more.

Another option is to make voting period always end at non-fixed time. For example calculate a random value between zero and 60 seconds and subtract that from the voting period end time. This would add significant risk for people attempting to snipe near the end.

**Comment by ChoooseGaute** [comment]
What do you think of the option to use the 'wait for quiet' scheme (“Using
‘Wait for Quiet’ voting in The DAO” @dominic_w
https://medium.com/@dominic_w/using-wait-for-quiet-voting-in-the-dao-12ecd9d9ccc3)
or similar / adaptations thereof.

Cheers,
Gaute

**Comment by sss-CRS-sss** [comment]
I think the random time of the end of the period is impossible. A decrease in the strength of the voice will more affect the "strength of the crowd" (small holders). When someone creates a "bad" article anyone can launch "a wave" of messages with a call "downvote" the article. If the power of the voice decreases, then all the activities of the community should be like a school of fish - at one point and all at once have to do one thing. But this is impossible.
