### ISSUE TITLE
Editor rewards should be proportional to value of their contributions

### ISSUE THREAD

**Issue by contractormario** [EveripediaNetwork/Everipedia#17]
This is to prevent abuse where people would create edits that don't bring any value, only to reap the rewards.

This is a hard problem that most likely has no best solution, but any solution would still be better than no solution.

Some ideas (naive):
* IQ per character (longer edits = bigger rewards; would lead to wordy padded articles)
* scale reward based on total number of votes cast
* machine learning algo to judge value of edits (probably best automated approach; but need special kind of training data)

**Comment by k26dr** [comment]
There is a simple way to solve this and that is to use voter input as a proxy for quality. Any other way is gameable.

**Comment by k26dr** [comment]
Rewards are already scaled based on votes gained, so agreed on that
