### ISSUE TITLE
Rewards are not processed for periods when server was offline

### ISSUE THREAD

**Issue by contractormario** [EveripediaNetwork/Everipedia#18]
https://github.com/EveripediaNetwork/Everipedia/blob/eda8de7bbd776f67c2dd258bad9a1302de004d2d/eparticlectr/eparticlectr.cpp#L454

I can't reproduce this myself, but seems to me that if server crashes and later resumes operation, any reward periods missed during that downtime will not be processed.

**Comment by FortisFortuna** [comment]
You mean the everipedia.org server? It shouldn't matter since it goes of the endtime of the proposal.
