### ISSUE TITLE
Put a rewards indicator

### ISSUE THREAD

**Issue by x3pt** [EveripediaNetwork/Everipedia#19]
Put an indicator for estimated rewards on how much editors could get of all his/her work. In point of view it will motivate editors to do more if they know what to receive not just assuming how much they could have, it may leads to disappointment if their exception were not meet.

![iq](https://user-images.githubusercontent.com/35094960/48320396-c3b72080-e654-11e8-8cc8-9876b63e8fa9.png)

**Comment by k26dr** [comment]
rewards can be variable by period and I don't think a chance at a $1 reward is what motivates people to create content.
