### ISSUE TITLE
Limit users to vote

### ISSUE THREAD

**Issue by x3pt** [EveripediaNetwork/Everipedia#20]
This is to limit abusers where people create/edits and vote their own on a huge amount vote, only to reap the rewards.

![iq2](https://user-images.githubusercontent.com/35094960/48322550-1ac3f200-e663-11e8-9673-29940ebc36e0.png)

The possible solutions that I see;
 1. Set users max vote to 5 per article and there casting vote should be limit too maybe not more than 100 bp max.
 2. Set users max vote to 1 per article or until reach max limit of 500 bp votes per article per user.
 3. Split equally the 30min reward base of who participate within that time.

**Comment by k26dr** [comment]
I will include a form of this in this week's smart contract update.
