### ISSUE TITLE
Edit Typos in White Paper (no IQ token expected ;p)

### ISSUE THREAD

**Issue by jessethan** [EveripediaNetwork/Everipedia#5]
1. Under Initial Supply & Minting Schedule section:
Sentence currently reads: "An single editor’s contribution is valued based on the number and tiers of edits approved (Listing 1). The IQ reward available per day is determined by the daily minting formula (Listing 2)."
Correction - Replace "An" with "A"

2. Under Staking IQ Tokens section:
Sentence currently reads: "The second feature of the article module is usiing BP for token holder voting of inclusion or exclusion of proposed edits in queue."
Correction - Change "usiing" to "using"

**Comment by k26dr** [comment]
Whitepaper has been updated. This is no longer valid.
